# Site settings
title: Grand Prix Candi Murray
tag_text: Grand Prix Candi Murray
description: The GPCM is a Cyclocross Series composed of seven independently promoted CX races. These great independent races kick off the OBRA Cyclocross season and run from the start of September to the end of October. Riders from any state are welcome to race the GPCM. Series overall awards and prizes will be handed out at the GPCM series end party, in late October. Come experience some amazing cyclocross courses, competitive racing and exciting new race venues.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
